#   This template was generated by template_builder, the amazing and awesome Rails
#     application builder.
#
initializer 'generators.rb', <<-RUBY
  Rails.application.config.generators do |g|
end
RUBY
template = {'orm'=>'2mongo_mapper','database'=>'1mysql',}
recipes = template.values.flatten

@after = []
def after_bundler(&block); @after << block; end
