#   This template was generated by template_builder, the amazing and awesome Rails
#     application builder.
#
initializer 'generators.rb', <<-RUBY
  Rails.application.config.generators do |g|
  end
RUBY
template = {'orm'=>'mongo_mapper','database'=>'mysql'}
recipes = template.values.flatten

@after = []
def after_bundler(&block); @after << block; end

#  ---------------------------------------------------------------------------
# >----------------------------[ mongo_mapper]------------------------------<
gem 'bson_ext'
gem 'mongo_mapper'
gem 'mongo_mapper-rails3'
after_bundler do

gsub_file 'config/initializers/session_store.rb', 'active_record_store', 'mongo_mapper_store'
	generate 'mongo_mapper:config'

end

#  ---------------------------------------------------------------------------
# >----------------------------[ mysql]------------------------------<

# >-----------------------------[ Run Bundler ]-------------------------------<

say 'Running Bundler install. This will take a while.'
run 'bundle install'
say 'Running after Bundler callbacks.'
@after.each{|b| b.call}

# >---------------------------[ Install Command ]-----------------------------<
#  rails new APP_NAME -m toto.rb -O-d mysql
# >---------------------------------------------------------------------------<
