sqlite :
    command : sqlite3
    action :
oracle :
    command : -d oracle
    action :
mongo  :
    command :
    action :
ibm_db :
    command : -d ibm_db
    action :
redis :
    command :
    action :
postgres :
    command : -d postgresql
    action :
mysql :
    command : -d mysql
    action :
